### ISSUE TITLE
Logic error when using subnet annotations

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#103]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**: I tried to deploy Tarmak into an existing VPC. 

I used the following annotations on my hub (in zone A) in my tarmak.yaml:
```
annotations:
          tarmak.io/existing-vpc-id: vpc-12345678
          tarmak.io/existing-public-subnet-ids: subnet-public-A,subnet-public-B
          tarmak.io/existing-private-subnet-ids: subnet-private-A,subnet-private-B
```

And the following annotations on cluster1 (also in zone A):
```
annotations:
          tarmak.io/existing-vpc-id: vpc-12345678
          tarmak.io/existing-public-subnet-ids: subnet-public-A
          tarmak.io/existing-private-subnet-ids: subnet-private-A
```

The hub came up fine but when applying cluster1 I received the following error:
```
DEBU[0123] * aws_instance.kubernetes_etcd.1: Error launching source instance: InvalidParameterValue: Value (eu-west-1a) for parameter availabilityZone is invalid. Subnet 'subnet-3d5a7166' is in the availability zone eu-west-1b  app=tarmak command=terraform container=c92cb24713a4a94746ea1abf947165e63d36a98957bc692d87b5d62bc4e403cb module=terraform stack=kubernetes
```

**What you expected to happen**: I expected the subnet-*-B annotations to not interfere with the delpoyment of cluster1

**Anything else we need to know?**: This works if I remove the subnet-*-B annotations from the hub. The reason they were there is because I wanted to create a second cluster (cluster2) in the B subnets

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: AWS
- Install tools: tarmak
