### ISSUE TITLE
Add Jenkins module to Terraform stack

### ISSUE THREAD

**Issue by dippynark** [jetstack/tarmak#173]
We need to add a Jenkins module to the Terraform stack to configure Jenkins when bringing up environments. The following example `tarmak.yaml` snippet contains a typical Jenkins configuration for environments A and B:

- Jenkins will run in the environment A's hub as an instance pool
- Environment B references A's Jenkins instance
- All clusters in the B environment use A's Jenkins instance
- Any subsequent instances (e.g. prod) will also use A's Jenkins instance

```
environments:
- contact: tech@jetstack.io
  location: eu-west-2
  metadata:
    creationTimestamp: "2018-04-06T13:03:00Z"
    name: A
  privateZone: tarmak.local
  project: kubernetes
  provider: xyz-A
  jenkins:
    url: https://jenkins-in-A
    username: password
    password: (read from tarmak-config if not specified)
    prefix: (folder prefix, default empty) 
- contact: tech@jetstack.io
  location: eu-west-2
  metadata:
    creationTimestamp: "2018-04-06T13:03:00Z"
    name: B
  privateZone: tarmak.local
  project: kubernetes
  provider: xyz-B
  jenkins:
    url: https://jenkins-in-B
    username: password
    password: (read from tarmak-config if not specified)
    prefix: (folder prefix, default empty)
```

To configure HTTPS on the Jenkins loadbalancer, add the annotation `tarmak.io/jenkins-certificate-arn: <CRN>` to the metadata of the Jenkins instance pool.
