### ISSUE TITLE
Improve prometheus configuration 'modes' & node discovery

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/tarmak#349]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

Tarmak can provision an installation of prometheus to monitor the cluster it creates. It is turned on with:

```
kubernetes:
  prometheus:
    enabled: true
```

There is also a configuration option to have prometheus only scrape nodes that are _not_ k8s nodes (i.e. not masters workers etc). Is is enabled like this:

```
kubernetes:
  prometheus:
    ...
    externalScrapeTargetsOnly: true
```

These options don't enable a third valid mode where tarmak provisions the blackbox exporters on the nodes but doesn't install prometheus in the cluster.

Currently the service names for other instances (etcd) are hardcoded into the prometheus config - these would be better looked up with SRV records via DNS.

**What you expected to happen**:
A new setting that represents the tarmak prometheus mode, e.g.:

```
kubernetes:
  prometheus:
    enabled: true
    mode: default|blackboxOnly|externalScrapeTargetsOnly|...
```

Where the default mode is just install all the components as we do currently.

Tarmak should also providion SRV records for the etcd nodes to to allow prometheus to discover them.

**How to reproduce it (as minimally and precisely as possible)**:
N/A
