### ISSUE TITLE
Unable to create Jenkins instance pools

### ISSUE THREAD

**Issue by JoshVanL** [jetstack/tarmak#595]
/kind bug

**What happened**:
Tarmak errors when trying to template and a Jenkins instance pool is defined in the config.

$ tm cluster plan
INFO[0000] validating tarmak config                      app=tarmak
INFO[0000] verifying tarmak config                       app=tarmak
INFO[0005] writing SSH config                            app=tarmak
INFO[0005] ensuring remote resources                     app=tarmak
INFO[0007] running plan                                  app=tarmak
DEBU[0007] created temporary directory: /tmp/tarmak-assets624827073 
DEBU[0008] restored assets into directory: /tmp/tarmak-assets624827073 
ERRO[0008] Tarmak exited with an error: failed to prepare terraform: failed to generate code: 1 error occurred:
	* failed to execute template 'instance_pools': template: instance_pool_instance.tf.template:2:26: executing "instance_pool_instance.tf.template" at <.AmazonEBSEncrypted>: can't evaluate field AmazonEBSEncrypted in type interfaces.InstancePool

**What you expected to happen**:
Tarmak should be able to create Jenkins instance pools.

**How to reproduce it (as minimally and precisely as possible)**:
Add this instance pool to you current cluster

```
  - image: centos-puppet-agent
    maxCount: 1
    metadata:
      annotations:
          #tarmak.io/jenkins-certificate-arn: "arn:aws:acm:eu-west-1:228615251467:certificate/81e0c595-f5ad-40b2-8062-683b215bedcf"
      creationTimestamp: null
      name: jenkins
    minCount: 1
    size: large
    type: jenkins
    volumes:
    - metadata:
        creationTimestamp: null
        name: root
      size: 16Gi
      type: ssd
    - metadata:
        creationTimestamp: null
        name: data
      size: 16Gi
      type: ssd
```

**Anything else we need to know?**:
This break happened between 0.5-alpha2 and 0.5-alpha3. It seems to be related to EBS volume encryption.
